openapi: 3.0.0
info:
  title: Brokerage Account Management API
  description: API for managing brokerage accounts.
  version: 1.0.0

servers:
  - url: https://localhost:3500

paths:
  /bAccounts:
    post:
      summary: Create a new brokerage account
      description: Creates a new brokerage account with the provided details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BrokerageAccountCreateRequest"
      responses:
        "201":
          description: Brokerage account created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error

  /bAccounts/{accountId}:
    get:
      summary: Get a brokerage account by ID
      description: Retrieves details of a brokerage account based on the provided account ID.
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Brokerage account details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BrokerageAccount"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error

    patch:
      summary: Update brokerage account details (partial update)
      description: Updates specific details (balance, portfolio IDs, order IDs, transaction IDs, account status) of a brokerage account based on the provided account ID.
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BrokerageAccountUpdateRequest"
      responses:
        "200":
          description: Brokerage account updated
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error

    delete:
      summary: Delete a brokerage account
      description: Deletes a brokerage account based on the provided account ID.
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Brokerage account deleted
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error

components:
  schemas:
    BrokerageAccountCreateRequest:
      type: object
      required:
        - balance
        - userID
        - accountNumber
      properties:
        balance:
          type: number
          description: Current balance of the brokerage account.
          example: 10000.0
        userID:
          type: string
          description: Identifier for the user associated with the brokerage account.
          example: "user123"
        accountNumber:
          type: string
          description: Unique account number assigned by the brokerage firm.
          example: "ACC123456"

    BrokerageAccountUpdateRequest:
      type: object
      properties:
        balance:
          type: number
          description: New balance for the brokerage account.
          example: 15000.0
        portfolioIDs:
          type: array
          items:
            type: string
          description: New array of portfolio IDs associated with the brokerage account.
          example: ["portfolio1", "portfolio2"]
        orderIDs:
          type: array
          items:
            type: string
          description: New array of order IDs associated with the brokerage account.
          example: ["order1", "order2"]
        transactionIDs:
          type: array
          items:
            type: string
          description: New array of transaction IDs associated with the brokerage account.
          example: ["transaction1", "transaction2"]
        accountStatus:
          type: string
          enum: ["active", "suspended", "closed"]
          description: New status for the brokerage account.
          example: "suspended"
