openapi: 3.0.0
info:
  title: Stock Trading Trade Execution API
  description: API for executing trades in a stock trading platform
  version: 1.0.0
 
servers:
  - url: http://localhost:8080
    description: Production server
 
paths:
  /orders:
    post:
      summary: Place a new trade order
      requestBody:
        description: Trade order details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TradeOrder'
      responses:
        '201':
          description: Trade order placed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TradeOrderResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error
 
  /orders/{order_id}:
    get:
      summary: Get details of a specific trade order
      parameters:
        - name: order_id
          in: path
          description: ID of the trade order to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TradeOrderResponse'
        '404':
          description: Trade order not found
 
  /orders/{order_id}/cancel:
    post:
      summary: Cancel a specific trade order
      parameters:
        - name: order_id
          in: path
          description: ID of the trade order to cancel
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Trade order canceled successfully
        '404':
          description: Trade order not found
        '403':
          description: Forbidden
 
components:
  schemas:
    TradeOrder:
      type: object
      properties:
        symbol:
          type: string
        quantity:
          type: integer
        price:
          type: number
        order_type:
          type: string
          enum:
            - limit
            - market
        side:
          type: string
          enum:
            - buy
            - sell
 
    TradeOrderResponse:
      type: object
      properties:
        order_id:
          type: string
        symbol:
          type: string
        quantity:
          type: integer
        price:
          type: number
        order_type:
          type: string
        side:
          type: string
        status:
          type: string
          enum:
            - pending
            - filled
            - canceled
 
security:
  - bearerAuth: []
 
# components:
#   securitySchemes:
#     bearerAuth:
#       type: http
#       scheme: bearer
#       bearerFormat: JWT
 
tags:
  - name: Trade Execution
    description: Operations related to trade execution
